name: Build
run-name: Build actions
on:
  workflow_run: 
    workflows: [Tests]
    types: [completed]
permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: read
jobs:
  gh-root-meta:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    outputs:
      ROOT_META: ${{ steps.root_meta.outputs.root_meta }}
    steps:
      - name: Download a single artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test.yml
          name: gh-root-meta
          workflow_conclusion: success
      - name: set output
        id: root_meta
        run: |
          echo "root_meta=\"$(cat github-workflow-root.json | jq -c)\"" >> "${GITHUB_OUTPUT}"
  changed-files:
    name: Changed files
    needs: gh-root-meta
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      app: ${{ steps.filter.outputs.app }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Identify changed files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ fromJSON(needs.gh-root-meta.outputs.root_meta).event.before }}
          ref: ${{ fromJSON(needs.gh-root-meta.outputs.root_meta).event.head_ref }}
          filters: |
            app:
              - 'README.md'
  build:
    runs-on: ubuntu-latest
    needs: changed-files
    if: needs.changed-files.outputs.app == 'true'
    steps:
      - run: |
          echo running build
