name: Deploy
run-name: Deploy actions
on:
  workflow_run: 
    workflows: [Build]
    types: [completed]
permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: read
jobs:
  run-metadata:
    if: github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/run-metadata-download.yml
    with:
      from-workflow: build.yml

  changed-files:
    name: Changed files
    needs: run-metadata
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      app: ${{ steps.filter.outputs.app }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Identify changed files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ needs.run-metadata.outputs.base }}
          ref: ${{ needs.run-metadata.outputs.ref }}
          filters: |
            app:
              - 'README.md'

  deploy:
    runs-on: ubuntu-latest
    needs: [changed-files, run-metadata]
    env:
      base: ${{ needs.run-metadata.outputs.base }}
      ref: ${{ needs.run-metadata.outputs.ref }}
      extra: ${{ fromJson(needs.run-metadata.outputs.run-metadata.extras).next }}
    steps:
      - run: |
          echo 'Deploying'
          echo "${base}"
          echo "${ref}"
          echo "${extra}"
