name: Run metadata download
run-name: Run metadata download from artifacts
on:
  workflow_call:
    inputs:
      from-workflow:
        description: Workflow to download artifacts from.
        required: true
        type: string
    outputs:
      metadata: 
        description: Workflow run metadata
        value: ${{ jobs.run-metadata-download.outputs.run-metadata.metadata }}
      extras:
        description: Workflow run extras
        value: ${{ jobs.run-metadata-download.outputs.run-metadata.extras }}
      base:
        description: Used as param to path-filter.
        value: ${{ jobs.run-metadata-download.outputs.base }}
      ref:
        description: Used as param to path-filter.
        value: ${{ jobs.run-metadata-download.outputs.ref }}
jobs:
  run-metadata-download:
    runs-on: ubuntu-latest
    outputs:
      run-metadata: ${{ steps.run_metadata.outputs.run_metadata }}
      base: ${{ steps.refs.outputs.base }}
      ref: ${{ steps.refs.outputs.ref }}
    steps:
      - name: Download a single artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ inputs.from-workflow }}
          name: run-metadata
          workflow_conclusion: success

      - name: Sets output
        id: run_metadata
        run: |
          metadata="$(cat run-metadata.json | jq -r -c '.metadata')"
          extras="$(cat run-metadata.json | jq -r -c '.extras')"
          echo "metadata=$metadata" >> "${GITHUB_OUTPUT}"
          echo "extras=$extras" >> "${GITHUB_OUTPUT}"

      - name: Sets path filters helpers
        id: refs
        env:
          METADATA_EVENT_NAME: ${{ fromJson(steps.run_metadata.outputs.run_metadata.metadata).event_name }}
          METADATA_REF: ${{ fromJson(steps.run_metadata.outputs.run_metadata.metadata).ref }}
          METADATA_BASE_REF: ${{ fromJson(steps.run_metadata.outputs.run_metadata.metadata).base_ref }}
          METADATA_HEAD_REF: ${{ fromJson(steps.run_metadata.outputs.run_metadata.metadata).head_ref }}
          BEFORE: ${{ fromJson(steps.run_metadata.outputs.run_metadata.metadata).event.before }}
        run: |
          if [[ "${METADATA_EVENT_NAME}" == 'push' ]]; then
            base="${BEFORE}"
            ref="${METADATA_REF}"
          elif [[ "${METADATA_EVENT_NAME}" == 'pull_request' ]]; then
            base="${METADATA_BASE_REF}"
            ref="${METADATA_HEAD_REF}"
          fi

          echo "ref=${ref}" >> "${GITHUB_OUTPUT}"
          echo "base=${base}" >> "${GITHUB_OUTPUT}"
