name: Run metadata upload
run-name: Run metadata upload as artifact
on:
  workflow_call:
    inputs:
      custom-metadata:
        description: Forces custom metadata.
        default: '{}'
        required: false
        type: string
      extras:
        description: Extra json object to be merged on top of the default metadata.
        default: '{}'
        required: false
        type: string
jobs:
  run-metadata:
    runs-on: ubuntu-latest
    steps:
      - env:
          EXTRAS: ${{ toJson(inputs.extras) }}
          DEFAULT_METADATA: ${{ toJson(github) }}
          CUSTOM_METADATA: ${{ toJson(inputs.custom-metadata)}}
        run: |
          METADATA="${CUSTOM_METADATA}"
          
          if [ "${CUSTOM_METADATA}" = '{}' ]; then
            echo "Setting metadata as default github metadata..."
            METADATA="${DEFAULT_METADATA}"
          fi
          
          echo "${METADATA}" | jq -r -c '.|del(.token)|{metadata: .}' > github-run-metadata.json
          echo "${EXTRAS}" | jq -r -c > extras.json
          
          jq -s -r -c '.[0] * .[1]' extras.json github-run-metadata.json > run-metadata.json

      - name: upload root info
        uses: actions/upload-artifact@v3
        with:
          name: run-metadata
          path: run-metadata.json
          retention-days: 1
